name: "Run Unit tests"

on:
  push:
    branches:
    - main
    - staging
    - develop

env:
  PROJECT_PATH: 'WpfDemoApp.Test/WpfDemoApp.Test.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  deploy:
    name: 'Run Tests'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: 'Restore workload'
      run: dotnet workload restore ${{ env.PROJECT_PATH }}

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --verbosity normal
