name: "Build in Release"

on:
  push:
    branches:
      - main
      - staging
env:
  PROJECT_PATH: 'WpfDemoApp/WpfDemoApp.sln'
  OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  build:
    name: 'Build WpfDemoApp'
    runs-on: 'windows-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: 'Restore workload'
        run: dotnet workload restore ${{ env.PROJECT_PATH }}

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release --output ${{ env.OUTPUT_DIRECTORY }}
