name: "Build in Release"

on:
  push:
    branches:
      - main
      - staging
env:
  PROJECT_PATH: WpfDemoApp\WpfDemoApp.csproj
  PROJECT_OUTPUT_PATH: ${{ github.workspace }}\output

jobs:
  build:
    name: 'Build WpfDemoApp'
    runs-on: 'windows-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: 'Restore workload'
        run: dotnet workload restore ${{ env.PROJECT_PATH }}

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build project'
        run: dotnet publish ${{ env.PROJECT_PATH }} --no-restore --configuration Release --output ${{ env.PROJECT_OUTPUT_PATH }} 

      - name: Display structure of downloaded files
        run: ls -R ${{ env.PROJECT_OUTPUT_PATH }}
        
      - name: 'Upload Build Artifact'
        uses: actions/download-artifact@v4
        with:
          name: Wpf
          path: ${{ env.PROJECT_OUTPUT_PATH }}

     
