name: "Build in Release"

on:
  push:
    branches:
      - main
      - staging
env:
  PROJECT_PATH: 'WpfDemoApp\WpfDemoApp.csproj'
  PROJECT_RELEASE_PATH: 'D:\a\demo\demo\WpfDemoApp\bin\Release\net9.0-windows\publish\'
  OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  build:
    name: 'Build WpfDemoApp'
    runs-on: 'windows-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: 'Restore workload'
        run: dotnet workload restore ${{ env.PROJECT_PATH }}

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build project'
        run: dotnet publish ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: Display structure of downloaded files
        run: ls -R ${{ env.PROJECT_RELEASE_PATH }}
        
      - name: 'Upload Build Artifact'
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ${{ env.PROJECT_RELEASE_PATH }}

     
